# Generated by Django 2.2.5 on 2019-09-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0002_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='users.Interest'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='api_posts',
        ),
    ]
